version: '3'
services:
  redoc:
    image: redocly/redoc
    container_name: redoc
    ports:
      - 8081:80
    volumes:
      - ./docs/openapi/output/index.yml:/usr/share/nginx/html/index.yml
    environment:
      SPEC_URL: index.yml
    depends_on:
      swagger-watch:
        condition: service_healthy
  swagger-watch:
    build: ./swagger-watch
    container_name: swagger-watch
    volumes:
      - ./swagger-watch:/app
      - /app/node_modules
      - ./docs/openapi/src:/docs/openapi/src
      - ./docs/openapi/output:/docs/openapi/output
    environment:
      INPUT_PATH: ./docs/openapi/src/index.yml
      OUTPUT_PATH: ./docs/openapi/output/index.yml
      WATCH_PATH: ./docs/openapi/src/**
    healthcheck:
      test: ["CMD-SHELL", "test -e /docs/openapi/output/index.yml"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 5s
    working_dir: /app
    command: 'node index.js'
